### ISSUE TITLE
zdb monitor raises an error

### ISSUE THREAD

**Issue by islamTaha12** [threefoldtech/0-templates#104]
![image](https://user-images.githubusercontent.com/17981089/45596679-e7951780-b9bf-11e8-91cd-f014ecba692f.png)

**env**
js development
0-robot development

**Comment by serboctor** [comment]
This is not a bug. In all of our services we check if the service is installed in the monitor action and if it is not installed you'll see this error in the logs when it checks the state. This has been the case ever since we started creating 0-robot templates and it has already been discussed before.
