### ISSUE TITLE
Container couldn't authorize itself on zerotier

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/0-templates#201]
### Information: 
```
container_data = {'nics': [{'name': 'af180969cc', 'type': 'zerotier', 'id': <zt_id>, 'token': <token>}, {'type': 'default', 'name': 'defaultnic'}], 'flist': 'https://hub.grid.tf/tf-bootable/ubuntu:16.04.flist', 'storage': 'zdb://hub.grid.tf:9900', 'mounts': [], 'initProcesses': [], 'hostNetwprking': False, 'hostname': '954861a866399c0ba417d9', 'ports': [], 'zerotierNetwork': '', 'privileged': False, 'env': []}
```
### Steps:
1- Put zerotier token and id into this data.
2- Create container with it.
### Actual Result
container couldn't authorize itself.
![image](https://user-images.githubusercontent.com/41957921/48123673-3013d780-e283-11e8-935a-5b64bd46a2e3.png)

**Comment by zaibon** [comment]
This issue is actually non valid.
Now that we are moving toward a 3bot world where the 3bot is responsible to manage primitive capacity deployed on a node. The authorization of a container in a zerotier network needs to be done by the 3bot itself, not the container template.

The only thing the container template needs to do, is to allow the 3bot to see the zerotier identify of the container.
