### ISSUE TITLE
Testcases for node template

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/0-templates#267]
Template: [node](https://github.com/threefoldtech/0-templates/tree/development/templates/node)
- Add testcases to cover node template.

**Comment by john-kheir** [comment]
- here are the tests: https://github.com/threefoldtech/0-templates/blob/development_960/tests/testcases/a_basics/node_testcases.py
- Reboot is not done just because that's the node we are using for the other tests.
- Also create_zdb_namespace and zdb_path action are not done since they are already tested by the namespace and zdb  install
